# Generated by Django 3.2.12 on 2024-03-27 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название дисциплины')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тема')),
                ('task', models.TextField(default='Дз', verbose_name='Задание')),
                ('deadline', models.DateTimeField(verbose_name='Срок сдачи')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hw_board.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия пользователя')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=250, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='HwDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=50, verbose_name='Содержание')),
                ('mark', models.IntegerField(verbose_name='Оценка')),
                ('hw_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hw_board.homeworktype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hw_board.student', verbose_name='Студент')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='hw_board.Student'),
        ),
    ]
